In [10]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [11]:
import pandas as pd 
import numpy as np
dataset_labeled = pd.read_csv('HotelReservationsModified.csv').drop(['Booking_ID'], axis=1)
dataset_labeled

no_of_adults  no_of_children  lead_time  arrival_year  arrival_month  \
0                 2               0        224          2017             10   
1                 2               0          5          2018             11   
2                 1               0          1          2018              2   
3                 2               0        211          2018              5   
4                 2               0         48          2018              4   
...             ...             ...        ...           ...            ...   
36270             3               0         85          2018              8   
36271             2               0        228          2018             10   
36272             2               0        148          2018              7   
36273             2               0         63          2018              4   
36274             2               0        207          2018             12   

       arrival_date  no_of_special_requests  type_of_meal_plan_Meal Plan 2  \
0                 2                       0                          False   
1                 6                       1                          False   
2                28                       0                          False   
3                20                       0                          False   
4                11                       0                          False   
...             ...                     ...                            ...   
36270             3                       1                          False   
36271            17                       2                          False   
36272             1                       2                          False   
36273            21                       0                          False   
36274            30                       0                          False   

       room_type_reserved_Room_Type 1  room_type_reserved_Room_Type 4  \
0                                True                           False   
1                                True                           False   
2                                True                           False   
3                                True                           False   
4                                True                           False   
...                               ...                             ...   
36270                           False                            True   
36271                            True                           False   
36272                            True                           False   
36273                            True                           False   
36274                            True                           False   

       room_type_reserved_Room_Type 6  market_segment_type_Offline  \
0                               False                         True   
1                               False                        False   
2                               False                        False   
3                               False                        False   
4                               False                        False   
...                               ...                          ...   
36270                           False                        False   
36271                           False                        False   
36272                           False                        False   
36273                           False                        False   
36274                           False                         True   

       market_segment_type_Online  booking_status_Canceled  \
0                           False                    False   
1                            True                    False   
2                            True                     True   
3                            True                     True   
4                            True                     True   
...                           .

In [12]:
dataset_labeled.columns
columns = []

columns.append('label_avg_price_per_room')
for i in range(len(dataset_labeled.columns[:-1])):
    columns.append(dataset_labeled.columns[i])

dataset_labeled = dataset_labeled[columns]
dataset_labeled

label_avg_price_per_room  no_of_adults  no_of_children  lead_time  \
0                             1             2               0        224   
1                             2             2               0          5   
2                             1             1               0          1   
3                             2             2               0        211   
4                             2             2               0         48   
...                         ...           ...             ...        ...   
36270                         3             3               0         85   
36271                         2             2               0        228   
36272                         2             2               0        148   
36273                         2             2               0         63   
36274                         3             2               0        207   

       arrival_year  arrival_month  arrival_date  no_of_special_requests  \
0              2017             10             2                       0   
1              2018             11             6                       1   
2              2018              2            28                       0   
3              2018              5            20                       0   
4              2018              4            11                       0   
...             ...            ...           ...                     ...   
36270          2018              8             3                       1   
36271          2018             10            17                       2   
36272          2018              7             1                       2   
36273          2018              4            21                       0   
36274          2018             12            30                       0   

       type_of_meal_plan_Meal Plan 2  room_type_reserved_Room_Type 1  \
0                              False                            True   
1                              False                            True   
2                              False                            True   
3                              False                            True   
4                              False                            True   
...                              ...                             ...   
36270                          False                           False   
36271                          False                            True   
36272                          False                            True   
36273                          False                            True   
36274                          False                            True   

       room_type_reserved_Room_Type 4  room_type_reserved_Room_Type 6  \
0                               False                           False   
1                               False                           False   
2                               False                           False   
3                               False                           False   
4                               False                           False   
...                               ...                             ...   
36270                            True                           False   
36271                           False                           False   
36272                           False                           False   
36273                           False                           False   
36274                           False                           False   

       market_segment_type_Offline  market_segment_type_Online  \
0                             True                       False   
1                            False                        True   
2                            False                        True   
3                            False                        True   
4                            False                        True   
...                            ...         

In [13]:
# let variables between 0-2 for xgboost use
def xgboost_label(room_price_label):
    if room_price_label == 1:
        return 0
    elif room_price_label == 2:
        return 1
    else:
        return 2

In [14]:
dataset_labeled['label_avg_price_per_room'] = dataset_labeled['label_avg_price_per_room'].apply(lambda x: xgboost_label(x))

In [15]:
dataset_labeled

label_avg_price_per_room  no_of_adults  no_of_children  lead_time  \
0                             0             2               0        224   
1                             1             2               0          5   
2                             0             1               0          1   
3                             1             2               0        211   
4                             1             2               0         48   
...                         ...           ...             ...        ...   
36270                         2             3               0         85   
36271                         1             2               0        228   
36272                         1             2               0        148   
36273                         1             2               0         63   
36274                         2             2               0        207   

       arrival_year  arrival_month  arrival_date  no_of_special_requests  \
0              2017             10             2                       0   
1              2018             11             6                       1   
2              2018              2            28                       0   
3              2018              5            20                       0   
4              2018              4            11                       0   
...             ...            ...           ...                     ...   
36270          2018              8             3                       1   
36271          2018             10            17                       2   
36272          2018              7             1                       2   
36273          2018              4            21                       0   
36274          2018             12            30                       0   

       type_of_meal_plan_Meal Plan 2  room_type_reserved_Room_Type 1  \
0                              False                            True   
1                              False                            True   
2                              False                            True   
3                              False                            True   
4                              False                            True   
...                              ...                             ...   
36270                          False                           False   
36271                          False                            True   
36272                          False                            True   
36273                          False                            True   
36274                          False                            True   

       room_type_reserved_Room_Type 4  room_type_reserved_Room_Type 6  \
0                               False                           False   
1                               False                           False   
2                               False                           False   
3                               False                           False   
4                               False                           False   
...                               ...                             ...   
36270                            True                           False   
36271                           False                           False   
36272                           False                           False   
36273                           False                           False   
36274                           False                           False   

       market_segment_type_Offline  market_segment_type_Online  \
0                             True                       False   
1                            False                        True   
2                            False                        True   
3                            False                        True   
4                            False                        True   
...                            ...         

In [16]:
from sklearn.model_selection import train_test_split

df_treinamento, df_teste = train_test_split(dataset_labeled, test_size=0.3, random_state=40)

In [17]:
df_treinamento.shape

(25392, 16)

In [18]:
df_teste.shape

(10883, 16)

In [19]:
X_teste = df_teste.iloc[:,1:len(dataset_labeled)].astype('float32').values
X_teste

array([[  2.,   0., 192., ...,   0.,   0.,   1.],
       [  2.,   1.,  29., ...,   1.,   1.,   0.],
       [  2.,   0.,   9., ...,   1.,   1.,   0.],
       ...,
       [  2.,   0.,  68., ...,   1.,   0.,   1.],
       [  2.,   0., 159., ...,   0.,   0.,   1.],
       [  1.,   0.,  15., ...,   0.,   0.,   1.]], dtype=float32)

In [20]:
X_teste.shape

(10883, 15)

In [21]:
Y_teste = df_teste.iloc[:, 0].astype('float32').values
Y_teste

array([0., 2., 2., ..., 1., 0., 1.], dtype=float32)

In [22]:
Y_teste.shape

(10883,)

In [23]:
df_treinamento.astype('float32').to_csv('hotel-reservations-train-xgboost.csv', header = False, index = False)
df_teste.astype('float32').to_csv('hotel-reservations-test-xgboost.csv', header = False, index = False)

In [24]:
import collections

collections.Counter(df_treinamento['label_avg_price_per_room'])

Counter({1: 9473, 2: 8276, 0: 7643})

In [25]:
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=40, sampling_strategy = 'not minority')

In [26]:
X_resampled, y_X_resampled = rus.fit_resample(df_treinamento.iloc[:,1:len(dataset_labeled)].astype('float32').values, df_treinamento.iloc[:, 0].astype('float32').values)

In [27]:
collections.Counter(y_X_resampled)

Counter({0.0: 7643, 1.0: 7643, 2.0: 7643})

In [28]:
t = pd.DataFrame(X_resampled)
t.insert(0, column=1000, value = y_X_resampled)
t

1000  0     1      2       3     4     5     6     7     8     9     \
0       0.0   1.0   0.0    2.0  2018.0   4.0  20.0   1.0   0.0   1.0   0.0   
1       0.0   2.0   0.0  142.0  2018.0   8.0  22.0   1.0   0.0   1.0   0.0   
2       0.0   2.0   0.0   42.0  2018.0   4.0  24.0   1.0   0.0   1.0   0.0   
3       0.0   1.0   0.0   11.0  2017.0  10.0  19.0   0.0   0.0   1.0   0.0   
4       0.0   2.0   0.0   41.0  2017.0  11.0   8.0   1.0   0.0   0.0   1.0   
...     ...   ...   ...    ...     ...   ...   ...   ...   ...   ...   ...   
22924   2.0   2.0   0.0    7.0  2018.0   2.0  11.0   1.0   1.0   1.0   0.0   
22925   2.0   1.0   0.0  111.0  2018.0  10.0  10.0   0.0   0.0   1.0   0.0   
22926   2.0   3.0   0.0   77.0  2018.0   7.0   3.0   2.0   0.0   0.0   1.0   
22927   2.0   2.0   1.0   40.0  2018.0  11.0   6.0   0.0   0.0   1.0   0.0   
22928   2.0   3.0   0.0   65.0  2018.0   7.0  26.0   0.0   0.0   0.0   1.0   

       10    11    12    13    14    
0       0.0   0.0   0.0   0.0   1.0  
1       0.0   0.0   1.0   0.0   1.0  
2       0.0   0.0   1.0   0.0   1.0  
3       0.0   1.0   0.0   0.0   1.0  
4       0.0   1.0   0.0   0.0   1.0  
...     ...   ...   ...   ...   ...  
22924   0.0   1.0   0.0   0.0   1.0  
22925   0.0   1.0   0.0   1.0   0.0  
22926   0.0   0.0   1.0   0.0   1.0  
22927   0.0   1.0   0.0   0.0   1.0  
22928   0.0   0.0   1.0   1.0   0.0  

[22929 rows x 16 columns]

In [29]:
t.to_csv('hotel-reservations-train-xgboost.csv', header = False, index = False)

In [30]:
import sagemaker
import boto3
from sagemaker import Session

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml


In [ ]:
# set default credentials
boto3.setup_default_session(region_name='us-east-1')

# create session
session = sagemaker.Session()

# define bucket, folders and keys
bucket = ''
subpasta_modelo = 'modelos/hotelreservations/xgboost-undersampling'
subpasta_dataset = 'dataset/hotelreservations'
key_train = 'hotel-train-data-xgboost'
key_test = 'hotel-test-data-xgboost'

role = sagemaker.get_execution_role()

# paths for train and test
s3_train_data = 's3://{}/{}/train/{}'.format(bucket, subpasta_dataset, key_train)
s3_test_data = 's3://{}/{}/test/{}'.format(bucket, subpasta_dataset, key_test)
output_location = 's3://{}/{}/output'.format(bucket, subpasta_modelo)

In [32]:
import os
with open('hotel-reservations-train-xgboost.csv', 'rb') as f:
  boto3.Session().resource('s3').Bucket(bucket).Object(os.path.join(subpasta_dataset, 'train', key_train)).upload_fileobj(f)

In [33]:
with open('hotel-reservations-test-xgboost.csv', 'rb') as f:
    boto3.Session().resource('s3').Bucket(bucket).Object(os.path.join(subpasta_dataset, 'test', key_test)).upload_fileobj(f)

In [34]:
from sagemaker import image_uris
container = image_uris.retrieve(framework = 'xgboost', region=boto3.Session().region_name, version='latest')

In [35]:
xgboost = sagemaker.estimator.Estimator(
    image_uri = container,
    role = role,
    instance_count = 1,
    instance_type = 'ml.m5.2xlarge',
    output_path = output_location,
    sagemaker_session = session
)

In [36]:
xgboost.set_hyperparameters(
    num_round=200,
    objective='multi:softprob',
    num_class=3
)

In [37]:
train_input = sagemaker.inputs.TrainingInput(s3_data = s3_train_data, content_type='csv', s3_data_type = 'S3Prefix')
validation_input = sagemaker.inputs.TrainingInput(s3_data = s3_test_data, content_type='csv', s3_data_type = 'S3Prefix')
data_channels = {'train': train_input, 'validation': validation_input}

In [ ]:
xgboost.fit(data_channels)

### Deploy

In [ ]:
xgboost_regressor = xgboost.deploy(initial_instance_count = 1, instance_type = 'ml.m4.xlarge')

In [40]:
from sagemaker.serializers import CSVSerializer
xgboost_regressor.serializer = CSVSerializer()

In [41]:
X_teste.shape, type(X_teste)

((10883, 15), numpy.ndarray)

In [42]:
previsoes_bytes = xgboost_regressor.predict(X_teste)
previsoes_str = previsoes_bytes.decode('utf-8')
previsoes_list = eval(previsoes_str)
previsoes_array = np.array(previsoes_list)
previsoes_array

array([[5.38174689e-01, 4.09321696e-01, 5.25035858e-02],
       [5.48313153e-07, 4.64053737e-05, 9.99953032e-01],
       [5.36750117e-03, 8.07456225e-02, 9.13886905e-01],
       ...,
       [3.87069643e-01, 5.73459625e-01, 3.94707359e-02],
       [8.78979743e-01, 1.20685093e-01, 3.35221353e-04],
       [3.38642627e-01, 6.61315262e-01, 4.21201803e-05]])

In [43]:
predicted_labels = np.argmax(previsoes_array, axis=1)
predicted_labels

array([0, 2, 2, ..., 1, 0, 1])

In [44]:
Y_teste = np.array(Y_teste)
Y_teste

array([0., 2., 2., ..., 1., 0., 1.], dtype=float32)

In [45]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

accuracy = accuracy_score(Y_teste, predicted_labels)
precision = precision_score(Y_teste, predicted_labels, average='macro')
recall = recall_score(Y_teste, predicted_labels, average='macro')
f1 = f1_score(Y_teste, predicted_labels, average='macro') 

In [46]:
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Accuracy: 0.8256914453735184
Precision: 0.8274832125538539
Recall: 0.8289967945866853
F1 Score: 0.8278641541405278


In [47]:
print(classification_report(Y_teste, predicted_labels))

              precision    recall  f1-score   support

         0.0       0.84      0.82      0.83      3308
         1.0       0.79      0.77      0.78      4127
         2.0       0.85      0.90      0.87      3448

    accuracy                           0.83     10883
   macro avg       0.83      0.83      0.83     10883
weighted avg       0.83      0.83      0.83     10883



In [48]:
cm = confusion_matrix(Y_teste, predicted_labels)
cm

array([[2701,  521,   86],
       [ 454, 3192,  481],
       [  47,  308, 3093]])