In [1]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd 
import numpy as np
dataset_labeled = pd.read_csv('HotelReservations.csv').drop(['Booking_ID'], axis=1)
dataset_labeled

no_of_adults  no_of_children  no_of_weekend_nights  no_of_week_nights  \
0                 2               0                     1                  2   
1                 2               0                     2                  3   
2                 1               0                     2                  1   
3                 2               0                     0                  2   
4                 2               0                     1                  1   
...             ...             ...                   ...                ...   
36270             3               0                     2                  6   
36271             2               0                     1                  3   
36272             2               0                     2                  6   
36273             2               0                     0                  3   
36274             2               0                     1                  2   

       required_car_parking_space  lead_time  arrival_year  arrival_month  \
0                               0        224          2017             10   
1                               0          5          2018             11   
2                               0          1          2018              2   
3                               0        211          2018              5   
4                               0         48          2018              4   
...                           ...        ...           ...            ...   
36270                           0         85          2018              8   
36271                           0        228          2018             10   
36272                           0        148          2018              7   
36273                           0         63          2018              4   
36274                           0        207          2018             12   

       arrival_date  repeated_guest  ...  room_type_reserved_Room_Type 6  \
0                 2               0  ...                           False   
1                 6               0  ...                           False   
2                28               0  ...                           False   
3                20               0  ...                           False   
4                11               0  ...                           False   
...             ...             ...  ...                             ...   
36270             3               0  ...                           False   
36271            17               0  ...                           False   
36272             1               0  ...                           False   
36273            21               0  ...                           False   
36274            30               0  ...                           False   

       room_type_reserved_Room_Type 7  market_segment_type_Aviation  \
0                               False                         False   
1                               False                         False   
2                               False                         False   
3                               False                         False   
4                               False                         False   
...                               ...                           ...   
36270                           False                         False   
36271                           False                         False   
36272                           False                         False   
36273                           False                         False   
36274                           False                         False   

       market_segment_type_Complementary  market_segment_type_Corporate  \
0                                  False                          False   
1                                  False                          False   
2                                  False                          False   
3                                  False               

In [4]:
dataset_labeled.columns
columns = []

columns.append('label_avg_price_per_room')
for i in range(len(dataset_labeled.columns[:-1])):
    columns.append(dataset_labeled.columns[i])

dataset_labeled = dataset_labeled[columns]
dataset_labeled

label_avg_price_per_room  no_of_adults  no_of_children  \
0                             1             2               0   
1                             2             2               0   
2                             1             1               0   
3                             2             2               0   
4                             2             2               0   
...                         ...           ...             ...   
36270                         3             3               0   
36271                         2             2               0   
36272                         2             2               0   
36273                         2             2               0   
36274                         3             2               0   

       no_of_weekend_nights  no_of_week_nights  required_car_parking_space  \
0                         1                  2                           0   
1                         2                  3                           0   
2                         2                  1                           0   
3                         0                  2                           0   
4                         1                  1                           0   
...                     ...                ...                         ...   
36270                     2                  6                           0   
36271                     1                  3                           0   
36272                     2                  6                           0   
36273                     0                  3                           0   
36274                     1                  2                           0   

       lead_time  arrival_year  arrival_month  arrival_date  ...  \
0            224          2017             10             2  ...   
1              5          2018             11             6  ...   
2              1          2018              2            28  ...   
3            211          2018              5            20  ...   
4             48          2018              4            11  ...   
...          ...           ...            ...           ...  ...   
36270         85          2018              8             3  ...   
36271        228          2018             10            17  ...   
36272        148          2018              7             1  ...   
36273         63          2018              4            21  ...   
36274        207          2018             12            30  ...   

       room_type_reserved_Room_Type 5  room_type_reserved_Room_Type 6  \
0                               False                           False   
1                               False                           False   
2                               False                           False   
3                               False                           False   
4                               False                           False   
...                               ...                             ...   
36270                           False                           False   
36271                           False                           False   
36272                           False                           False   
36273                           False                           False   
36274                           False                           False   

       room_type_reserved_Room_Type 7  market_segment_type_Aviation  \
0                               False                         False   
1                               False                         False   
2                               False                         False   
3                               False                         False   
4                               False                         False   
...                               ...                           ...   
36270                           False                         False   
36271                      

In [5]:
# let variables between 0-2 for xgboost use
def xgboost_label(room_price_label):
    if room_price_label == 1:
        return 0
    elif room_price_label == 2:
        return 1
    else:
        return 2

In [6]:
dataset_labeled['label_avg_price_per_room'] = dataset_labeled['label_avg_price_per_room'].apply(lambda x: xgboost_label(x))

In [7]:
dataset_labeled

label_avg_price_per_room  no_of_adults  no_of_children  \
0                             0             2               0   
1                             1             2               0   
2                             0             1               0   
3                             1             2               0   
4                             1             2               0   
...                         ...           ...             ...   
36270                         2             3               0   
36271                         1             2               0   
36272                         1             2               0   
36273                         1             2               0   
36274                         2             2               0   

       no_of_weekend_nights  no_of_week_nights  required_car_parking_space  \
0                         1                  2                           0   
1                         2                  3                           0   
2                         2                  1                           0   
3                         0                  2                           0   
4                         1                  1                           0   
...                     ...                ...                         ...   
36270                     2                  6                           0   
36271                     1                  3                           0   
36272                     2                  6                           0   
36273                     0                  3                           0   
36274                     1                  2                           0   

       lead_time  arrival_year  arrival_month  arrival_date  ...  \
0            224          2017             10             2  ...   
1              5          2018             11             6  ...   
2              1          2018              2            28  ...   
3            211          2018              5            20  ...   
4             48          2018              4            11  ...   
...          ...           ...            ...           ...  ...   
36270         85          2018              8             3  ...   
36271        228          2018             10            17  ...   
36272        148          2018              7             1  ...   
36273         63          2018              4            21  ...   
36274        207          2018             12            30  ...   

       room_type_reserved_Room_Type 5  room_type_reserved_Room_Type 6  \
0                               False                           False   
1                               False                           False   
2                               False                           False   
3                               False                           False   
4                               False                           False   
...                               ...                             ...   
36270                           False                           False   
36271                           False                           False   
36272                           False                           False   
36273                           False                           False   
36274                           False                           False   

       room_type_reserved_Room_Type 7  market_segment_type_Aviation  \
0                               False                         False   
1                               False                         False   
2                               False                         False   
3                               False                         False   
4                               False                         False   
...                               ...                           ...   
36270                           False                         False   
36271                      

In [8]:
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(dataset_labeled, test_size=0.3, random_state=40)

In [9]:
df_train.shape

(25392, 32)

In [10]:
df_test.shape

(10883, 32)

In [11]:
X_test = df_test.iloc[:,1:len(dataset_labeled)].astype('float32').values
X_test

array([[2., 0., 2., ..., 0., 0., 1.],
       [2., 1., 2., ..., 1., 1., 0.],
       [2., 0., 2., ..., 1., 1., 0.],
       ...,
       [2., 0., 2., ..., 1., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [12]:
X_test.shape

(10883, 31)

Transforma no array do numpy com os atributos classificatório.

In [13]:
Y_test = df_test.iloc[:, 0].astype('float32').values
Y_test

array([0., 2., 2., ..., 1., 0., 1.], dtype=float32)

In [14]:
Y_test.shape

(10883,)

In [15]:
df_train.astype('float32').to_csv('hotel-reservations-train-xgboost.csv', header = False, index = False)
df_test.astype('float32').to_csv('hotel-reservations-test-xgboost.csv', header = False, index = False)

In [16]:
import collections

collections.Counter(df_train['label_avg_price_per_room'])

Counter({1: 9473, 2: 8276, 0: 7643})

In [17]:
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=40, sampling_strategy = 'not minority')

In [18]:
X_resampled, y_X_resampled = rus.fit_resample(df_train.iloc[:,1:len(dataset_labeled)].astype('float32').values, df_train.iloc[:, 0].astype('float32').values)

In [19]:
collections.Counter(y_X_resampled)

Counter({0.0: 7643, 1.0: 7643, 2.0: 7643})

In [20]:
t = pd.DataFrame(X_resampled)
t.insert(0, column=1000, value = y_X_resampled)
t

1000  0     1     2     3     4      5       6     7     8     ...  \
0       0.0   1.0   0.0   0.0   1.0   0.0    2.0  2018.0   4.0  20.0  ...   
1       0.0   2.0   0.0   2.0   5.0   0.0  142.0  2018.0   8.0  22.0  ...   
2       0.0   2.0   0.0   2.0   5.0   0.0   42.0  2018.0   4.0  24.0  ...   
3       0.0   1.0   0.0   1.0   2.0   0.0   11.0  2017.0  10.0  19.0  ...   
4       0.0   2.0   0.0   2.0   3.0   0.0   41.0  2017.0  11.0   8.0  ...   
...     ...   ...   ...   ...   ...   ...    ...     ...   ...   ...  ...   
22924   2.0   2.0   0.0   0.0   3.0   0.0    7.0  2018.0   2.0  11.0  ...   
22925   2.0   1.0   0.0   1.0   0.0   0.0  111.0  2018.0  10.0  10.0  ...   
22926   2.0   3.0   0.0   3.0   5.0   0.0   77.0  2018.0   7.0   3.0  ...   
22927   2.0   2.0   1.0   2.0   0.0   0.0   40.0  2018.0  11.0   6.0  ...   
22928   2.0   3.0   0.0   0.0   3.0   0.0   65.0  2018.0   7.0  26.0  ...   

       21    22    23    24    25    26    27    28    29    30    
0       0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0  
1       0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0  
2       0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0  
3       0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  
4       0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
22924   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  
22925   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0  
22926   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0  
22927   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  
22928   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0  

[22929 rows x 32 columns]

In [21]:
t.to_csv('hotel-reservations-train-xgboost.csv', header = False, index = False)

### SageMaker


In [22]:
import sagemaker
import boto3
from sagemaker import Session

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml


In [ ]:
# set default credentials
boto3.setup_default_session(region_name='us-east-1')

# create session
session = sagemaker.Session()

# define bucket, folders and keys
bucket = ''
subfolder_model = 'models/hotelreservations/xgboost-undersampling'
subfolder_dataset = 'dataset/hotelreservations'
key_train = 'hotel-train-data-xgboost'
key_test = 'hotel-test-data-xgboost'

role = sagemaker.get_execution_role()

# paths for train and test
s3_train_data = 's3://{}/{}/train/{}'.format(bucket, subfolder_dataset, key_train)
s3_test_data = 's3://{}/{}/test/{}'.format(bucket, subfolder_dataset, key_test)
output_location = 's3://{}/{}/output'.format(bucket, subfolder_model)

In [24]:
import os
with open('hotel-reservations-train-xgboost.csv', 'rb') as f:
  boto3.Session().resource('s3').Bucket(bucket).Object(os.path.join(subfolder_dataset, 'train', key_train)).upload_fileobj(f)

In [25]:
with open('hotel-reservations-test-xgboost.csv', 'rb') as f:
    boto3.Session().resource('s3').Bucket(bucket).Object(os.path.join(subfolder_dataset, 'test', key_test)).upload_fileobj(f)

### Train XGBoost

In [26]:
from sagemaker import image_uris
container = image_uris.retrieve(framework = 'xgboost', region=boto3.Session().region_name, version='latest')

In [27]:
xgboost = sagemaker.estimator.Estimator(
    image_uri = container,
    role = role,
    instance_count = 1,
    instance_type = 'ml.m5.2xlarge',
    output_path = output_location,
    sagemaker_session = session
)

In [28]:
xgboost.set_hyperparameters(
    num_round=200,
    objective='multi:softprob',
    num_class=3
)

In [29]:
train_input = sagemaker.inputs.TrainingInput(s3_data = s3_train_data, content_type='csv', s3_data_type = 'S3Prefix')
validation_input = sagemaker.inputs.TrainingInput(s3_data = s3_test_data, content_type='csv', s3_data_type = 'S3Prefix')
data_channels = {'train': train_input}

In [30]:
xgboost.fit(data_channels)

INFO:sagemaker:Creating training-job with name: xgboost-2024-05-23-17-35-36-737


2024-05-23 17:35:36 Starting - Starting the training job...
2024-05-23 17:35:55 Starting - Preparing the instances for training...
2024-05-23 17:36:25 Downloading - Downloading input data...
2024-05-23 17:36:40 Downloading - Downloading the training image...
2024-05-23 17:37:16 Training - Training image download completed. Training in progress..Arguments: train
[2024-05-23:17:37:34:INFO] Running standalone xgboost training.
[2024-05-23:17:37:34:INFO] Path /opt/ml/input/data/validation does not exist!
[2024-05-23:17:37:34:INFO] File size need to be processed in the node: 4.84mb. Available memory size in the node: 23887.34mb
[2024-05-23:17:37:34:INFO] Determined delimiter of CSV input is ','
[17:37:34] S3DistributionType set as FullyReplicated
[17:37:34] 51348x31 matrix with 1137084 entries loaded from /opt/ml/input/data/train?format=csv&label_column=0&delimiter=,
[17:37:34] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 114 extra nodes, 0 pruned nodes, max_depth=6
[17:37:34] s

### Deploy 

In [ ]:
xgboost_regressor = xgboost.deploy(initial_instance_count = 1, instance_type = 'ml.m4.xlarge')

In [32]:
from sagemaker.serializers import CSVSerializer
xgboost_regressor.serializer = CSVSerializer()

In [33]:
X_test.shape, type(X_test)

((10883, 31), numpy.ndarray)

In [34]:
predict_bytes = xgboost_regressor.predict(X_test)
predict_str = predict_bytes.decode('utf-8')
predict_list = eval(predict_str)
predict_array = np.array(predict_list)
predict_array

array([[8.01501274e-01, 1.78988844e-01, 1.95098128e-02],
       [7.25095815e-05, 5.07372944e-03, 9.94853795e-01],
       [6.60328716e-02, 4.63370860e-01, 4.70596254e-01],
       ...,
       [2.57297605e-01, 6.68849587e-01, 7.38528222e-02],
       [7.47730196e-01, 2.50448406e-01, 1.82139361e-03],
       [6.45996034e-01, 3.47535819e-01, 6.46818336e-03]])

In [35]:
predicted_labels = np.argmax(predict_array, axis=1)
predicted_labels

array([0, 2, 2, ..., 1, 0, 0])

In [36]:
Y_test = np.array(Y_test)
Y_test

array([0., 2., 2., ..., 1., 0., 1.], dtype=float32)

In [37]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

accuracy = accuracy_score(Y_test, predicted_labels)
precision = precision_score(Y_test, predicted_labels, average='macro')
recall = recall_score(Y_test, predicted_labels, average='macro')
f1 = f1_score(Y_test, predicted_labels, average='macro') 

In [38]:
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Accuracy: 0.837452908205458
Precision: 0.8388536718581795
Recall: 0.841948417867531
F1 Score: 0.839717796587223


In [39]:
print(classification_report(Y_test, predicted_labels))

              precision    recall  f1-score   support

         0.0       0.86      0.85      0.86      3308
         1.0       0.82      0.77      0.79      4127
         2.0       0.84      0.90      0.87      3448

    accuracy                           0.84     10883
   macro avg       0.84      0.84      0.84     10883
weighted avg       0.84      0.84      0.84     10883



In [40]:
cm = confusion_matrix(Y_test, predicted_labels)
cm

array([[2811,  423,   74],
       [ 406, 3184,  537],
       [  39,  290, 3119]])